server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的服务名称
    cloud:
      config:
        server:
          git:
            skipSslValidation: true # 跳过ssl认证
            uri: https://github.com/930053262/springcloud-config.git  #GitHub上复制的项目地址
#服务注册到?eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka